server:
  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
spring:
  redis:
    host: localhost
    port: 6379
    password: testtest1234
  data:
    redis:
      serializer: jackson
  session:
    store-type: redis
    redis:
      namespace: test:session
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: <YOUR NAME>
    password: <YOUR PASSWORD>
  jpa:
    show-sql: true
    generate-ddl=false: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <YOUR CLIENT ID>
            client-secret: <YOUR SECRETS>
            scope:
              - email
              - profile
